version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "jossmoff"
    commit-message:
      prefix: "chore(dep):"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "jossmoff"
    commit-message:
      prefix: "chore(dep):"
